name: Data updater every 6 hours

on:
  schedule:
  - cron: 0 */6 * * *
  
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Update lists
        run: ./updaters/update-6-hours.sh
          
      - name: Commit files if changed
        run: ./commit.sh ${{ secrets.GITHUB_TOKEN }} "sources/"
