name: Data updater every 15 days

on:
  schedule:
  - cron: 0 0 */15 * *
  
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Update lists
        run: ./updaters/update-15-days.sh
          
      - name: Commit files if changed
        run: ./commit.sh ${{ secrets.GITHUB_TOKEN }} "sources/"
