name: Data updater



on:
  schedule:
  - cron: 0 * * * *
  
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update lists
        run: ./update.sh

      - name: Switching from HTTPS to SSH
        run: git remote set-url origin git@github.com:molangning/fire-av.git

      - name: Stage our changed lists
        run: git add sources/

      - name: Configure git email and username
        run: |
          git config --local user.email "example@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Check git status and save to output
        id: myoutputs
        run: |
          git status
          echo "::set-output name=gitstatus::$(git status --porcelain)"
          
      - name: Commit changed files
        if: steps.myoutputs.outputs.gitstatus != ''
        run: git commit -m "[Github Action] Automated updated lists."

      - name: Push changes # push the output folder to your repo
        if: steps.myoutputs.outputs.gitstatus != ''
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
