name: Data updater every 3 days

on:
  schedule:
  - cron: 0 0 */3 * *
  
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update lists
        run: ./updaters/update-3-days.sh
          
      - name: Commit files if changed
        run: |
          git add -N .

          if [ -z "$(git ls-files --modified sources/)" ]; then
              echo "[+] No files were changed"
          else
              echo "[+] Files were changed! Pushing changed..."
              git fetch -a
              git stage sources/
              git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
              git config --local user.email "example@github.com"
              git config --local user.name "GitHub Action"
              git commit -m "[Github Action] Automated lists update."
              git push
          fi
